spring:
  h2:
    console:
      enabled: true # http://localhost:8080/h2-console/
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:~/testdb
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0